name = "JuliaTutorial"
uuid = "76b57c1f-f2e9-426d-8d72-3d7628398bf3"
authors = ["Olivier Labayle"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
